### ISSUE TITLE
Add precompiled robot-js binaries for new node version modules

### ISSUE THREAD

**Issue by jguze** [Robot/node-robot#12]
Can we add more precompiled binaries to http://node.getrobot.net/ for newer versions of node.

It v7 , they increased the NODE_VERSION_MODULES:
v7: **51** https://github.com/nodejs/node/commit/b5bdff876ba62ed58664eb011a863d0960f4089b

This bit us pretty bad because we never noticed that it failed to download the binary after upgrading node. Any chance we can add that in?

**Comment by dkrutsko** [comment]
Hey there, since it's becoming a huge problem now, I'm going to start work on this right away. The main issue is that I'll need to make some changes to the code in order to get it to compile but it shouldn't take long. My apologies for the delay and for breaking your project.

**Comment by dkrutsko** [comment]
I'm gonna close this issue as it is duplicated by #5.
