### ISSUE TITLE
Robot-js 2.0 ship list

### ISSUE THREAD

**Issue by dkrutsko** [Robot/node-robot#17]
* #43, #44: Updated all copyright headers to 2018
* #5, #16, #26, #14: Added support for Node 7, 8 & 9
* #13, #19: Fixed and updated the README file
* #6, #22: Added integrity checks for binary files ([Adv-201](https://nodesecurity.io/advisories/201))
* #28, #30: Added NPM and Yarn lock files
* #32, #35: Reorganized the entire project structure
	* #4: Replaced the build pipeline with node-gyp
	* #36: Added version info to Windows binary
	* #37: Added basic automated testing support
	* #2: Resolved issues surrounding Electron
* #46, #47: Removed support for Windows Vista ([why?](https://github.com/Robot/robot/issues/56))
* #50, #53: Copy Windows PDB files during compilation
* #25, #54: Added experimental support for Raspberry Pi
	* Precompiled binaries for linux on arm are provided

**Comment by karliky** [comment]
Amazing work here!! 💪🏼

**Comment by dkrutsko** [comment]
@karliky Thanks! Your OC inbox is full but thanks for all the amazing work you've done on the talks! And Bugcraft Studio looks amazing, truly inspirational work! Sorry this release has taken so long but I'm hoping that will start to improve as I get back into this project again!
