### ISSUE TITLE
Update support for Node.js ^8

### ISSUE THREAD

**Issue by acuper** [Robot/node-robot#26]
Currently there is not binaries for node 8 (57) https://github.com/Robot/robot-js-binaries/tree/gh-pages/addon/1.0.2

Are you planning to add it soon ?

**Comment by dkrutsko** [comment]
The good news is that the current dev branch already supports Node 8. I just need to get #20 merged and we'll be golden. I'll work on getting it done this week. Sorry, I've been way distracted with other crap :-(
