### ISSUE TITLE
nw-gyp or node-gyp

### ISSUE THREAD

**Issue by kkm** [Robot/node-robot#4]
I need binding.gyp from node-gyp. can you script for me?

thanks.

**Comment by dkrutsko** [comment]
Although the project makes use of node-gyp for downloading the node.js libraries, the project itself is compiled with Visual Studio on windows or G++/Clang++ on Linux and Mac via a makefile. Is there a reason you need a binding.gyp file?

**Comment by dkrutsko** [comment]
Might get resolved by #2.

**Comment by kkm** [comment]
I need this project for nwjs with node-webkit thats why I need this script for compile. I hope you get my answer.

**Comment by dkrutsko** [comment]
There's currently a pull request to fix this issue (#20), I'll be working on integrating it this weekend along with #21 which should finish off [version 1.1.0](https://github.com/Robot/robot-js/milestone/1).

**Comment by p120ph37** [comment]
@kkm, if you want to try out #20 before @dkrutsko finishes merging, you can temporarily set the `robot-js` dependency version in your project to this value: `"https://github.com/p120ph37/robot-js/archive/dev.tar.gz"`
