### ISSUE TITLE
Project description is misleading

### ISSUE THREAD

**Issue by quinton-ashley** [Robot/node-robot#41]
This project still fails to install with the latest version of node LTS 8.9.3.  It has been over two months since this project has been incompatible with node LTS.  Please do not claim to support node.js in this project's description if LTS "updates" will continue to not be supported in the future, this is the bare minimum of support required for a project to claim it supports node.  Preparation to support 8.9.x should have taken place before it was made the LTS version, this issue #26 was first brought up in August!  This project's description is misleading to developers as long as LTS compatibility is not maintained.  I know this is an open source project but time must be set aside to maintain a project with a constantly evolving language like node.js.  It's obvious that incredible amounts of works went into this project and it's one of my favorite packages for node.js so please don't let it go to waste by maintaining it unreliably.  When developers depend on a package and build whole apps around their functionality there can't be gaps in coverage for the LTS versions of node.  I doubt I am the only dev that wants to use this library to make client-side local apps and needs prebuilt binaries to be available.  Don't let trying to reach big milestones, implementing other features, or even fixing bugs get in the way of crucial updates.

**Comment by quinton-ashley** [comment]
I found a well maintained package with similar functionality that's compatible with LTS versions of node:
[https://github.com/octalmage/robotjs](https://github.com/octalmage/robotjs)

**Comment by dkrutsko** [comment]
You're absolutely right, I have fixed this problem in version 2.0.0. Additional info [here](https://github.com/Robot/robot-js/issues/42#issuecomment-375991053).
