### ISSUE TITLE
Update support for Node.js ^7

### ISSUE THREAD

**Issue by dkrutsko** [Robot/node-robot#5]
A new Node.js major release is now available and with that, a new modules version (51). Robot-js needs to be patched and tested with this new version.

**Comment by Disorrder** [comment]
+1

**Comment by Disorrder** [comment]
Node 7.8.0 already published and 8.0 nightly version, but still no progress here :( I'd like to use two versions of Node.js but it's problem in Windows (okay on os x with n). Please, man

**Comment by dkrutsko** [comment]
I'll start working on getting this fixed right away. Time is moving way too quickly for me :-(

**Comment by dkrutsko** [comment]
Okay, pull #14 appears to resolve the compiling issues. See [this](https://github.com/nodejs/nan/issues/587) issue for technical details about the deprecated functions as well as [this](https://github.com/nodejs/nan/blob/master/nan_private.h) code, which is where my solution came from. I'll work on getting this merged and released soon.
