### ISSUE TITLE
Get current cursor state

### ISSUE THREAD

**Issue by CraigZych** [Robot/node-robot#57]
This is probably more of a feature request but is there any way to get the current mouse state? (Ie. Pointer, hand, text, etc)

I'm creating a remote desktop app and would like to be able to match the client cursor. 

Also is there any way to tell if your currently active on a typable area so I can trigger the mobile keyboard?

**Comment by dkrutsko** [comment]
mmm, this would be more of a feature request for [robot/robot](https://github.com/robot/robot). I went ahead and movied your issue there: [robot/robot#106](https://github.com/Robot/robot/issues/106).
