### ISSUE TITLE
keyboard hold key sticky

### ISSUE THREAD

**Issue by Disorrder** [Robot/node-robot#59]
Hello. If I press a key, wait some time and release, I have no "sticky" effect like `aaaaaaaaaaaaaaaaaa`:
```javascript
var kb = new robot.Keyboard();
kb.press(robot.KEY_A);
robot.Timer.sleep(2000);
kb.release(robot.KEY_A);
kb.click(robot.KEY_BACKSPACE);
```
I have tried `setTimeout` also, but no luck

**Comment by dkrutsko** [comment]
Hey there, so the way the internal API's work, at least for Windows, is one `press`/`release` is one click. You have to keep looping that code to repeat it. It was this way from my testing at least. For repeating, you may have to simulate a real keyboard. If you would like more information let me know but I was able to set up an Arduino Micro and communicate to it through [serialport](https://www.npmjs.com/package/serialport) to simulate "real" keys. Might work better for you.

**Comment by Disorrder** [comment]
wow, not necessary :) Loop is maybe okay

**Comment by dkrutsko** [comment]
The reason I bring it up is in case you have applications scanning for injected (or fake) input that just gets thrown away. You'd either have to solve it by using some sort of keyboard driver or real hardware. Anyways, hope this helps. Good luck!
