### ISSUE TITLE
How can I make press key not described?

### ISSUE THREAD

**Issue by factoryal** [Robot/node-robot#64]
Hi.

I want to press the key operators in numberpad like ' + * - ...
But I cannot find what keyword points that key.
Is another way to make press that key?

Thanks.
(sorry for my English)

**Comment by dkrutsko** [comment]
Hey there, try:
```
KeyAdd      | {NUM+}
KeySubtract | {NUM-}
KeyMultiply | {NUM*}
KeyDivide   | {NUM/}
KeyDecimal  | {NUM.}
KeyEnter    | {NUM~}
```
See [this section](http://getrobot.net/api/keyboard.html#Compile) for more

**Comment by factoryal** [comment]
Thanks!
But.. OMG... I confused the repository that has very simillar name.
I'm developing in JS. It has a little performance issue that makes some latency in key input.
I'll try again in C if there's no more improvements.

**Comment by dkrutsko** [comment]
Are you talking about [robotjs](https://github.com/octalmage/robotjs)? Yeah that's mainly my fault, both libraries came out around the same time, I didn't know it existed until a week before the release of my library.

**Comment by factoryal** [comment]
Yeah that's right.
Some keys are not described in that [API page](https://robotjs.io/docs/syntax).
There's no merges for the additional keys not supported yet.
I'm about to give up... but now I found it's source of source files.
I'll try with this repository.

**Comment by factoryal** [comment]
AND.... It perfectly WORKS!!
I had to look for more repositories.
Thanks for your support.

**Comment by dkrutsko** [comment]
I'm glad to hear your issue is fixed.
