### ISSUE TITLE
keyboard type

### ISSUE THREAD

**Issue by OussamaAlouat** [Robot/node-robot#65]
Hello! I need to change the layout of the keyboard for the project I'm currently working.
I need a Spanish keyboard. Would it be possible?

Thanks in advance.

**Comment by dkrutsko** [comment]
I'm not sure I understand your question. The constants are consistent with what the operating system provides. If a particular constant is not provided by robot, you can simply create whatever constant you need. For example: `keyboard.click (96);`.

**Comment by OussamaAlouat** [comment]
The problem is that I need record when someone press some keys. I need store the keys pressed in a  Spanish keyboard and Robotjs doesn't provide codes for 'ñ' or 'ALT GR' keys that are present in that kind of keyboard.

Is there some way to store codes for keys pressed in different layouts or create my own equivalences in Robotjs?

**Comment by dkrutsko** [comment]
See if you can use [`GetState`](http://getrobot.net/api/keyboard.html#GetState) with the number representing `ñ`, 164 or 165 I think. I'm not completely sure how these characters work on Windows, but someone mentioned [scan codes](https://github.com/Robot/robot/issues/22) which I'll look into implementing.

**Comment by OussamaAlouat** [comment]
Hello again.

I read in the [docs](http://getrobot.net/api/keyboard.html#GetState2) that GetState checks the pressed state of all keys system-wide. The point is: on Windows when I start my application and I call GetState in the first line, the result is an object with some keys pressed... (my expectations were no key pressed).

How can it be? There are something that I am not understanding?

**Comment by dkrutsko** [comment]
There's two versions of the function, one where you pass to it a key, and another where you pass nothing and it returns an array of all keys. Which keys does it say are being pressed?

**Comment by OussamaAlouat** [comment]
The second one, I want to retrieve every key's states.
Thanks.

**Comment by dkrutsko** [comment]
Yeah I think at the moment, you need to do what I suggested above, and enter your keys manually for keys not supported by robot. It's the only thing that will solve your problem immediately and is basically how the array version of the function works.

**Comment by OussamaAlouat** [comment]
Ok, from the beginning. I am developing a multiplatform application and I am using the second version of [getState](http://getrobot.net/api/keyboard.html#GetState2) method to record every key pressed or released. On linux, all works as expected, but on Windows is different. For example, when I press the CTRL KEY, sometimes I recive two codes (17 & 162) but other times I recive only one (17).

Is this a normal behaviour on Windows? I don't think so but I don't understand why it is happening this?

NOTE: I want to clarify that problem only happens on Windows. My tests on Linux works perfectly.

**Comment by dkrutsko** [comment]
Honestly, that function just redirects to [GetAsyncKeyState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646293(v=vs.85).aspx). Hopefully the Microsoft documentation can provide the answer you're looking for.

**Comment by OussamaAlouat** [comment]
Hello again.

In this case, I'm trying to write the '<' symbol on Windows using your library, but I don't know which code is. So, first I did `console.log(robot.Keyboard.compile('{<}'));` and the output shown in console was: `[ { down: true, key: 8 }, { down: false, key: 8 } ]`, so I suposed the code to write '<' symbol is 8.

However, when I do `robot.Keyboard().click(8);` or `robot.Keyboard().press(8); robot.Keyboard().release(8);` nothing is shown in the console. What am I doing wrong? Why is the code not written as expected? Is this something normal?

I did this: 
```
  console.log(robot.Keyboard.compile('<')) // Output: [ { down: true, key: 8 }, { down: false, key: 8 } ]
  robot.Keyboard().click(8);
  robot.Keyboard().press(8);
  robot.Keyboard().release(8);
```

The output is: 
![captura](https://user-images.githubusercontent.com/32365517/43721245-94d1d40e-9992-11e8-9cab-81be62c06ef9.PNG)

**Comment by dkrutsko** [comment]
The `<` key represents backspace, see the table on [this page](http://getrobot.net/api/keyboard.html#Compile) for more. If you want to press the `<` key, you actually have to press `shift` + `,`. That's how you would press it on a regular US keyboard. I'm not sure if that key is different on non-US keyboards. I think I mentioned this above but on Linux, the keys are based on scan keys, which is really the way I should be handling it on Windows as well, but that'll most likely get supported in a future version of robot.
